services:
  rsshub:
    image: diygod/rsshub:chromium-bundled
    restart: unless-stopped
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: redis://redis:6379/
      LISTEN_INADDR_ANY: "1"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped

